version: '3.7'

networks:
  app-network:
    driver: bridge

volumes:
  data-volume:
    driver: local

services:
  pair:
    build:
      context: ./pair
      dockerfile: Dockerfile
    image: pest2-training/pair:local
    volumes:
      - ./pair/:/app
    restart: unless-stopped
    command: "tail -f /dev/null"
    networks:
      - app-network
  db:
    image: mariadb:10.6
    logging:
      options:
        max-size: "5m"
        max-file: "1"
    volumes:
      - ./volumes/db:/var/lib/mysql
    restart: unless-stopped
    depends_on:
      - pair
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_DATABASE=laravel
      - MARIADB_USER=root
      - MARIADB_PASSWORD=root
      - MARIADB_INITDB_SKIP_TZINFO=GMT
    networks:
      - app-network
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    image: pest2-training/web:local
    logging:
      options:
        max-size: "10m"
        max-file: "1"
    volumes:
      - ./web:/var/www/html
    ports:
      - 80:80
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - app-network
  selenium:
    image: selenium/standalone-chrome:4.3
    volumes:
      - /dev/shm:/dev/shm
    environment:
      - SE_START_VNC=false
    ports:
      - 4444:4444
      - 7900:7900
    networks:
      - app-network
